#
# Module manifest for module 'MrRemoteDesktop'
#
# Generated by: Mike F Robbins
#
# Generated on: 09/23/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MrRemoteDesktop.psm1'

DscResourcesToExport = 'RemoteDesktop'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '30fa4e0e-5233-4eae-ac2d-853e7b9fd8dc'

# Author of this module
Author = 'Mike F Robbins'

# Company or vendor of this module
CompanyName = 'mikefrobbins.com'

# Copyright statement for this module
Copyright = '(c) 2016 Mike F Robbins. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module with DSC Resource for enabling RDP access to a Computer'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

}
